### ISSUE TITLE
DDatHome-go在CentOS7.6上编译运行后，只显示一行就不动了

### ISSUE THREAD

**Issue by Janet-Baker** [dd-center/DDatHome-go#3]
DDatHome x86_64 for linux (built on CentOS7.6, golang-1.13.11-1.el7.x86_64)

第1次尝试
编译指令：`go build main.go`
成品URL:
`https://linode.indlut.cn/tmp/DDatHome-go`，大小9764KB
实测，打开之后就显示一行`Dial wss://cluster.vtbs.moe/?runtime=go&version=1.0.1&platform=linux&name=LittleFatty`，然后什么都没了

第2次尝试
感觉不太对，换了一套编译指令
`go build -ldflags "-s -w" -o DDatHome-x86_64`
成品在`https://linode.indlut.cn/tmp/DDatHome-go-x86_64`，大小7172KB
跑一圈，感觉没啥区别，都是只显示一行提示就没反应了。

所以，就显示一行，是正常的吗？

**Comment by wudifeixue** [comment]
草，2年后由于更新about页面需要添加go，测试遇见了同样的问题，于是我来了。
这个我问了下@imlonghao 和@mrs4s 原因出在main.go的第166行，那行注释掉了，所以跑起来就是正常什么都不显示，在去掉注释的情况下，我的build完毕后已经正常显示可以使用。
不过由于情况比较迷惑，毕竟我也以为坏了，推荐去掉注释以后直接显示信息运行吧。
